version: '3.8'

services:
  sql-database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-database
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Ethernal123
    ports:
      - "1433:1433"
    networks:
      - my-network
    volumes:
      - ./DB/scripts/:/docker-entrypoint-initdb/scripts/
    command: >
      /bin/bash -c " /opt/mssql/bin/sqlservr & sleep 30 && /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P Ethernal123 -i /docker-entrypoint-initdb/scripts/2023.10.10_CreateBISdb.sql && wait "

  app:
    build: .
    container_name: app
    environment:
      - DB_ADDRESS=sql-database
      - DB_PORT=1433
      - DB_NAME=BIS
      - DB_PASSWORD=Ethernal123
      - SERVER_PORT=4000
    ports:
      - "4000:4000"
    depends_on:
      sql-database:
        condition: service_started
    networks:
      - my-network

  p2pmock:
    build:
      context: ./p2pmock
    container_name: p2pmock
    ports:
      - "5000:5000"
    networks:
      - my-network

networks:
  my-network:
