version: '3.8'

services:
  sql-database1:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-database1
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Ethernal123
    ports:
      - "1433:1433"
    networks:
      - my-network
    volumes:
      - ./app/DB/scripts/:/docker-entrypoint-initdb/scripts/
    command: >
      /bin/bash -c " /opt/mssql/bin/sqlservr & sleep 120 &&  /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P Ethernal123 -i /docker-entrypoint-initdb/scripts/2024.06.03_CreateBISdb.sql &&  /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P Ethernal123 -i /docker-entrypoint-initdb/scripts/2024.06.03_InsertData.sql &&  wait"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P Ethernal123 -Q \"IF EXISTS (SELECT name FROM sys.databases WHERE name = 'BIS') SELECT 1 ELSE SELECT 0\" | grep -q 1"
        ]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 2m

  app1:
    build:
      context: .
      dockerfile: image/Dockerfile
      args:
        - DNS_NAME=app1
    container_name: app1
    environment:
      - DB_ADDRESS=sql-database1
      - DB_PORT=1433
      - DB_NAME=BIS
      - DB_PASSWORD=Ethernal123
      - SERVER_PORT=4000
      - BENEFICIARY_BANK_URL=app2:4000
      - P2P_NODE_ADDRESS=p2pmock:5000
      - GPJC_API_ADDRESS=app1
      - GPJC_PORT=10501
      - BACKEND_API_ADDRESS=0.0.0.0:4000
    ports:
      - "4001:4000"
    depends_on:
      sql-database1:
        condition: service_healthy
    networks:
      - my-network

  sql-database2:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-database2
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Ethernal123
    ports:
      - "1434:1433"
    networks:
      - my-network
    volumes:
      - ./app/DB/scripts/:/docker-entrypoint-initdb/scripts/
    command: >
      /bin/bash -c " /opt/mssql/bin/sqlservr & sleep 120 &&  /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P Ethernal123 -i /docker-entrypoint-initdb/scripts/2024.06.03_CreateBISdb.sql &&  /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P Ethernal123 -i /docker-entrypoint-initdb/scripts/2024.06.03_InsertData.sql && /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P Ethernal123 -i /docker-entrypoint-initdb/scripts/2024.06.05_HLBPolicy.sql  && wait"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P Ethernal123 -Q \"IF EXISTS (SELECT name FROM sys.databases WHERE name = 'BIS') SELECT 1 ELSE SELECT 0\" | grep -q 1"
        ]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 2m

  app2:
    build:
      context: .
      dockerfile: image/Dockerfile
      args:
        - DNS_NAME=app2
    container_name: app2
    environment:
      - DB_ADDRESS=sql-database2
      - DB_PORT=1433
      - DB_NAME=BIS
      - DB_PASSWORD=Ethernal123
      - SERVER_PORT=4000
      - BENEFICIARY_BANK_URL=app1:4000
      - P2P_NODE_ADDRESS=p2pmock:5000
      - GPJC_API_ADDRESS=app2
      - GPJC_PORT=10501
      - BACKEND_API_ADDRESS=0.0.0.0:4000
    ports:
      - "4002:4000"
    depends_on:
      sql-database2:
        condition: service_healthy
    networks:
      - my-network

  p2pmock:
    build:
      context: ./p2pmock
    container_name: p2pmock
    environment:
      - BACKEND_URI1=http://localhost:4001/p2p
      - BACKEND_URI2=http://localhost:4002/p2p
      - BACKEND_URI3=http://localhost:4003/p2p
      - BACKEND_URI4=http://localhost:4004/p2p
      - PORT=5000
    ports:
      - "5000:5000"
    networks:
      - my-network

networks:
  my-network:
